"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { useState } from "react";
import { CogIcon, HomeIcon, Squares2X2Icon } from "@heroicons/react/24/outline";
import {
  CogIcon as solidCogIcon,
  HomeIcon as solidHomeIcon,
  Squares2X2Icon as solidSquares2X2Icon,
} from "@heroicons/react/24/solid";
import NavMenu from "@/components/nav.menu";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebarTopNavigation] = useState([
    {
      name: "本地壁纸",
      href: "/local",
      icon: HomeIcon,
      selectedIcon: solidHomeIcon,
      current: false,
    },
    {
      name: "社区",
      href: "/community",
      icon: Squares2X2Icon,
      selectedIcon: solidSquares2X2Icon,
      current: false,
    },
  ]);

  const [sidebarBottomNavigation] = useState([
    {
      name: "设置",
      href: "/settings/general",
      icon: CogIcon,
      selectedIcon: solidCogIcon,
      current: false,
    },
  ]);
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen bg-zinc-900">
          <div className="flex w-[74px] overflow-y-auto">
            <div className="flex flex-1 w-full flex-col items-center">
              <div className="w-full flex-1 space-y-1 px-1">
                {sidebarTopNavigation.map((item) => (
                  <NavMenu
                    key={item.name}
                    href={item.href}
                    name={item.name}
                    icon={item.icon}
                    selectedIcon={item.selectedIcon}
                    current={pathname === item.href}
                  />
                ))}
              </div>
              <div className="w-full px-1 mb-1">
                {sidebarBottomNavigation.map((item) => (
                  <NavMenu
                    key={item.name}
                    href={item.href}
                    name={item.name}
                    icon={item.icon}
                    selected-icon={item.selectedIcon}
                    current={pathname === item.href}
                  />
                ))}
              </div>
            </div>
          </div>

          {/* Content area */}
          <div className="flex flex-1 flex-col overflow-hidden bg-neutral-800 ml-1 rounded-l-lg">
            {/* Main content */}
            <div className="flex flex-1 items-stretch overflow-hidden">
              <main className="flex-1 overflow-y-auto">
                {/* Primary column */}
                <section
                  aria-labelledby="primary-heading"
                  className="flex h-full min-w-0 flex-1 flex-col lg:order-last"
                >
                  <h1 id="primary-heading" className="sr-only">
                    Photos
                  </h1>
                  {/* Your content */}
                  {children}
                </section>
              </main>

              {/* Secondary column (hidden on smaller screens) */}
              {/* <aside className="hidden w-96 overflow-y-auto border-l border-gray-200 bg-white lg:block"></aside> */}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
