/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ytV6yfBBi2j
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"

export function Test() {
  return (
    <div className="grid h-screen min-h-screen w-full overflow-hidden grid-cols-[280px_1fr]">
      <div className="border-r bg-primary-100/40 dark:bg-primary-800/40">
        <nav className="flex flex-col gap-4 px-4 py-6 text-sm font-medium">
          <Link
            className="flex items-center gap-3 rounded-lg px-3 py-2 text-primary-500 transition-all hover:text-primary-900 dark:text-primary-400 dark:hover:text-primary-50"
            href="#"
          >
            <svg
              className=" h-4 w-4"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
              <circle cx="12" cy="12" r="3" />
            </svg>
            常规
          </Link>
          <Link
            className="flex items-center gap-3 rounded-lg px-3 py-2 text-primary-500 transition-all hover:text-primary-900 dark:text-primary-400 dark:hover:text-primary-50"
            href="#"
          >
            <svg
              className=" h-4 w-4"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="8" cy="9" r="2" />
              <path d="m9 17 6.1-6.1a2 2 0 0 1 2.81.01L22 15V5a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2" />
              <path d="M8 21h8" />
              <path d="M12 17v4" />
            </svg>
            壁纸
          </Link>
          <Link
            className="flex items-center gap-3 rounded-lg px-3 py-2 text-primary-900 bg-primary-200 dark:bg-primary-700 dark:text-primary-50"
            href="#"
          >
            <svg
              className=" h-4 w-4"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M5 12s2.545-5 7-5c4.454 0 7 5 7 5s-2.546 5-7 5c-4.455 0-7-5-7-5z" />
              <path d="M12 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
              <path d="M21 17v2a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-2" />
              <path d="M21 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2" />
            </svg>
            外观
          </Link>
        </nav>
      </div>
      <div className="flex flex-col overflow-auto">
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="rounded-lg border border-primary-200 border-dashed dark:border-primary-800">
            <div className="flex items-center gap-2 px-6 py-4">
              <svg
                className=" h-6 w-6 text-primary-500 dark:text-primary-400"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M5 12s2.545-5 7-5c4.454 0 7 5 7 5s-2.546 5-7 5c-4.455 0-7-5-7-5z" />
                <path d="M12 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                <path d="M21 17v2a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-2" />
                <path d="M21 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2" />
              </svg>
              <h2 className="text-lg font-semibold">外观设置</h2>
            </div>
            <div className="px-6 py-4 space-y-4">
              <div className="flex items-center space-x-2">
                <Label htmlFor="dark-mode">Dark Mode</Label>
                <Switch id="dark-mode" />
              </div>
              <div>
                <Label htmlFor="color-theme">主题色</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="选择主题色" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectItem value="zinc">Zinc</SelectItem>
                      <SelectItem value="slate">Slate</SelectItem>
                      <SelectItem value="stone">Stone</SelectItem>
                      <SelectItem value="gray">Gray</SelectItem>
                      <SelectItem value="neutral">Neutral</SelectItem>
                      <SelectItem value="red">Red</SelectItem>
                      <SelectItem value="rose">Rose</SelectItem>
                      <SelectItem value="orange">Orange</SelectItem>
                      <SelectItem value="green">Green</SelectItem>
                      <SelectItem value="blue">Blue</SelectItem>
                      <SelectItem value="yellow">Yellow</SelectItem>
                      <SelectItem value="violet">Violet</SelectItem>
                    </SelectGroup>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
